#!/bin/sh


if [ $# -ne 1 ]; then
  echo "Usage : `basename ${BASH_SOURCE:-$0}` project_name"
  exit 1
fi


template_dir="~/bin/cpp_project_builder/template/project/"
project_name="$1"


mkdir "${project_name}"
cp -r "${template_dir}" "${project_name}/src/"
mv "${project_name}/src/core/include/VAR_PROJECT_NAME" "${project_name}/src/core/include/${project_name}"

substitute_command="s/VAR_PROJECT_NAME/${project_name}/g"
sed -i.bkp -e "${substitute_command}" "${project_name}/src/CMakeLists.txt"

rm "${project_name}/src/CMakeLists.txt.bkp"
